create table if not exists public.shelter_reports (
  id bigint generated by default as identity primary key,
  shelter_id text not null,
  shelter_name text not null,
  shelter_type text not null check (shelter_type in ('summer','winter')),
  report_type text not null,
  message text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);

alter table public.shelter_reports enable row level security;

create policy "public can insert shelter reports"
on public.shelter_reports
for insert
to anon, authenticated
with check (true);

create policy "public can read recent shelter reports"
on public.shelter_reports
for select
to anon, authenticated
using (created_at > now() - interval '24 hours');

create index if not exists shelter_reports_shelter_id_created_at_idx
on public.shelter_reports (shelter_id, created_at desc);

-- Existing crowd_reports table expected by src/data/crowd-reports.ts
create table if not exists public.crowd_reports (
  id bigint generated by default as identity primary key,
  shelter_name text not null,
  shelter_type text not null check (shelter_type in ('summer','winter')),
  status text not null check (status in ('여유','보통','혼잡')),
  created_at timestamptz not null default now()
);

alter table public.crowd_reports enable row level security;

create policy "public can insert crowd reports"
on public.crowd_reports
for insert
to anon, authenticated
with check (true);

create policy "public can read recent crowd reports"
on public.crowd_reports
for select
to anon, authenticated
using (created_at > now() - interval '3 hours');
